version: '3'

services:
  nginx:
    platform: linux/amd64
    build:
      context: .
      dockerfile: build/nginx/Dockerfile
    image: europe-west1-docker.pkg.dev/martaealessiosposi/website/nginx:1716741970
    environment:
      - VIRTUAL_HOST=martaealessiosposi.loc
      - VIRTUAL_PORT=80
    volumes:
      - ./src/:/usr/share/nginx/html
